import "../css/globals.css";

import HeaderComponent from "../component/header";
import FooterComponent from "../component/footer";
import Script from 'next/script';
//import Footer from "../component/footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  openGraph: {
    title: "My Next.js App",
    description: "A modern web application built with Next.js",
    images: [
      {
        url: "/logo.png",
        width: 800,
        height: 600,
        alt: "App Logo",
      },
    ],
    siteName: "My Next.js App",
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="wrapper">
          <HeaderComponent />
          {children}
          <FooterComponent />


        </div>

        <Script src="/js/common/modernizr.js"></Script>
          <Script src="/js/common.js"></Script>
          <Script src="/js/common/jquery-1.11.1.min.js"></Script>
          <Script src="/js/common/bootstrap.min.js"></Script>
          <Script src="/js/common/bootstrap-datepicker.js"></Script>
          <Script src="/js/common/chosen.min.js"></Script>
          <Script src="/js/common/bootstrap-checkbox.js"></Script>
          <Script src="/js/common/nice-scroll.js"></Script>
          <Script src="/js/common/jquery-browser.js"></Script>
          <Script src="/js/scripts.js"></Script>

      </body>
    </html>
  );
}
