import "../css/bootstrap.css";
import "../css/globals.css";
import "../css/bootstrap-datepicker.css";
import "../css/font-awesome.css";
import HeaderComponent from "../component/header";
import FooterComponent from "../component/footer";
import Script from "next/script";
import Head from "next/head";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  openGraph: {
    title: "My Next.js App",
    description: "A modern web application built with Next.js",
    images: [
      {
        url: "/images/logo.png",
        width: 800,
        height: 600,
        alt: "App Logo",
      },
    ],
    siteName: "My Next.js App",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link
          href="https://fonts.googleapis.com/css?family=Raleway:300,500,900%7COpen+Sans:400,700,400italic"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="../css/style.css" />
      </Head>
      <body>
        <div id="wrapper">
          <HeaderComponent />
          {children}
          <FooterComponent />
        </div>

       
        <Script src="/js/common/jquery-1.11.1.min.js"  />
        <Script src="/js/common/chosen.min.js"  />
        <Script src="/js/common/bootstrap.min.js"  />
        <Script src="/js/common/bootstrap-datepicker.js"  />
        <Script src="/js/common/bootstrap-checkbox.js"  />
        <Script src="/js/common/modernizr.js" />
        <Script src="/js/common.js"  />
        <Script src="/js/common/nice-scroll.js"  />
        <Script src="/js/common/jquery-browser.js"  />
        <Script src="/js/scripts.js"  />
      </body>
    </html>
  );
}